# Generated by Django 4.0.4 on 2022-05-05 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raterapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='rate',
            name='rate',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.CharField(max_length=100),
        ),
    ]
