# Generated by Django 4.0.4 on 2022-05-11 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raterapi', '0002_gamepicture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamepicture',
            name='action_pic',
        ),
        migrations.AddField(
            model_name='gamepicture',
            name='game_image',
            field=models.ImageField(null=True, upload_to='gamepictures'),
        ),
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
